import sys,json,html
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from app.metrics import accuracy,brier
from app.analytics import report
d=json.loads(Path("data/ledger.json").read_text());pred=d.get("predictions",[]);res=d.get("resolutions",[]);rm={r["prediction_id"]:r for r in res};sc=[]
for p in pred:
 r=rm.get(p["id"])
 if r and r["outcome"] in ("CORRECT","WRONG"):sc.append({"probability":p["probability"],"actual":1 if r["outcome"]=="CORRECT" else 0})
a=accuracy(sc);b=brier(sc);st=report(d);cards=""
for p in reversed(pred[-24:]):
 r=rm.get(p["id"]);o=r["outcome"] if r else "LOCKED";dc="up" if p["direction"]=="UP" else "down";oc="good" if o=="CORRECT" else("bad" if o=="WRONG" else "locked");ev={}
 for x in p.get("evidence",[]):
  if "=" in x:k,v=x.split("=",1);ev[k]=v
 cards+=f'<article class="call"><div class="top"><b>{html.escape(p["asset"])}</b><span class="status {oc}">{o}</span></div><div class="dir {dc}">{"↑" if p["direction"]=="UP" else "↓"} {p["direction"]}</div><div class="conf">{p["probability"]*100:.1f}<small>%</small></div><div class="lab">MODEL CONFIDENCE</div><div class="facts"><div><span>ENTRY</span><b>{html.escape(ev.get("entry","—"))}</b></div><div><span>TARGET</span><b>{p["target_pct"]:.2f}%</b></div><div><span>HORIZON</span><b>{p["horizon_hours"]}H</b></div></div><div class="hash">PROOF · {html.escape(p.get("proof_hash","")[:20])}…</div></article>'
if not cards:cards='<div class="empty">NO LOCKED CALLS YET. THE PUBLIC RECORD STARTS AT ZERO.</div>'
acc="—" if a is None else f"{a*100:.1f}%";bs="—" if b is None else f"{b:.3f}";edge=st.get("edge_status","INSUFFICIENT_DATA").replace("_"," ")
css='''*{box-sizing:border-box}body{margin:0;background:#05070a;color:#f5f7fb;font-family:Inter,system-ui,sans-serif}body:before{content:"";position:fixed;inset:0;pointer-events:none;background:radial-gradient(circle at 75% 5%,rgba(217,255,88,.09),transparent 30%)}.w{width:min(1220px,calc(100% - 36px));margin:auto}nav{height:82px;border-bottom:1px solid #1a202a;display:flex;align-items:center;justify-content:space-between}.brand{font-size:20px;font-weight:950}.acid,.up{color:#d9ff58}.down,.bad{color:#ff6978}.live,.lab{font-size:10px;letter-spacing:.13em;color:#778397}.hero{min-height:620px;display:grid;grid-template-columns:1.15fr .85fr;gap:60px;align-items:center}.kick{font-size:11px;letter-spacing:.2em;color:#d9ff58;font-weight:850}h1{font-size:clamp(72px,10vw,142px);line-height:.77;letter-spacing:-.085em;margin:22px 0 34px}.lead{font-size:21px;line-height:1.55;color:#9ca8ba}.panel{border:1px solid #26303e;background:linear-gradient(145deg,#10151d,#090c11);border-radius:24px;padding:26px}.big{font-size:78px;font-weight:950;margin:28px 0 0}.grid,.metrics{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:25px}.metric,.grid div{border:1px solid #202936;border-radius:12px;padding:15px}.metric span,.grid span,.facts span{display:block;color:#687487;font-size:9px;letter-spacing:.12em;margin-bottom:7px}.section{padding:65px 0}.head{display:flex;justify-content:space-between;align-items:end;border-bottom:1px solid #1a202a;padding-bottom:22px;margin-bottom:26px}h2{font-size:42px;letter-spacing:-.045em;margin:0}.head p{color:#738094}.metrics{grid-template-columns:repeat(5,1fr);margin:0}.metric b{font-size:24px}.calls{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.call{border:1px solid #202936;border-radius:18px;padding:20px;background:#0a0e14}.top{display:flex;justify-content:space-between}.status{font-size:9px;border:1px solid #303a49;border-radius:99px;padding:5px 8px}.good{color:#d9ff58}.dir{margin-top:26px;font-size:12px;font-weight:900}.conf{font-size:62px;font-weight:950;letter-spacing:-.06em}.conf small{font-size:24px}.facts{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:22px}.facts div{border-top:1px solid #202936;padding-top:10px;overflow:hidden}.facts b{font-size:11px}.hash{margin-top:18px;font:9px ui-monospace,monospace;color:#596477}.manifesto{margin:70px 0 90px;border:1px solid #283140;border-radius:24px;padding:42px}.manifesto h3{font-size:52px;letter-spacing:-.055em;margin:10px 0}.manifesto p{font-size:18px;color:#8d99ab;line-height:1.6}.empty{grid-column:1/-1;padding:40px;border:1px dashed #293341;color:#738094;border-radius:18px}footer{border-top:1px solid #1a202a;padding:30px 0 45px;color:#626e80;font-size:10px;display:flex;justify-content:space-between}@media(max-width:900px){.hero{grid-template-columns:1fr}.metrics{grid-template-columns:1fr 1fr}.calls{grid-template-columns:1fr 1fr}}@media(max-width:600px){.calls{grid-template-columns:1fr}h1{font-size:72px}}'''
page=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SEE IT COMING.</title><style>{css}</style></head><body><div class="w"><nav><div class="brand">SEE IT COMING<span class="acid">.</span></div><div class="live"><span class="acid">●</span> PUBLIC FORWARD EXPERIMENT · V1</div></nav><section class="hero"><div><div class="kick">PROOF BEFORE PERSUASION</div><h1>SEE IT<br>COMING.</h1><p class="lead">Can a machine detect the move before the market makes it? We do not claim it can. We lock the call first — then let reality answer.</p></div><div class="panel"><div class="live">PUBLIC RECORD · FORWARD ONLY</div><div class="big">{len(pred)}</div><div class="kick">LOCKED PREDICTIONS</div><div class="grid"><div><span>RESOLVED</span><b>{len(res)}</b></div><div><span>EDGE STATUS</span><b>{edge}</b></div><div><span>ACCURACY</span><b>{acc}</b></div><div><span>BRIER</span><b>{bs}</b></div></div></div></section><section class="section"><div class="head"><div><div class="kick">PUBLIC PROOF</div><h2>The scoreboard.</h2></div><p>Performance starts at zero. Nothing is backfilled.</p></div><div class="metrics"><div class="metric"><span>LOCKED</span><b>{len(pred)}</b></div><div class="metric"><span>RESOLVED</span><b>{len(res)}</b></div><div class="metric"><span>ACCURACY</span><b>{acc}</b></div><div class="metric"><span>BRIER</span><b>{bs}</b></div><div class="metric"><span>STATUS</span><b>{edge}</b></div></div></section><section class="section"><div class="head"><div><div class="kick">IMMUTABLE CALLS</div><h2>Locked before outcome.</h2></div><p>Direction, probability, target and horizon are committed before resolution.</p></div><div class="calls">{cards}</div></section><section class="manifesto"><div class="kick">THE STANDARD</div><h3>Wins stay. Losses stay.</h3><p>A signal is not an edge. A streak is not evidence. Credibility is earned through forward-locked calls, enough resolved observations, calibration and comparison with baselines.</p></section><footer><span>SEE IT COMING. · INTELLIGENCE, NOT HYPE.</span><span>EXPERIMENTAL · NOT FINANCIAL ADVICE</span></footer></div></body></html>'''
out=Path("site");out.mkdir(exist_ok=True);(out/"index.html").write_text(page);(out/"ledger.json").write_text(json.dumps(d,indent=2));print("Built premium dashboard")
